server:
  port: 8081

spring:
  application:
    name: checkout
  cloud:
    stream:
      bindings:
        orders:
          content-type: application/json
          destination: queue.delivery.orders
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /

stubrunner:
  ids: 'com.parisjug:inventory:+:stubs:8080'
  repository-root: 'git://https://github.com/ygrenzinger/contract-tests.git'
  stubs-per-consumer: true
  consumer-name: 'checkout'
  stubs-mode: remote