server:
  port: 8082

spring:
  cloud:
    stream:
      bindings:
        orders:
          content-type: application/json
          destination: queue.delivery.orders
          binder: local_rabbit
          group: orderMessageConsumers
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
                virtual-host: /

#stubrunner:
#  repositoryRoot: http://your-nexus-repo
#  ids:
#    - 'com.parisjug:inventory:+:stubs:8080'
#    - 'com.parisjug:checkout'
#  amqp:
#    enabled: true