---
request:
  method: "POST"
  url: "/v1/books"
  urlPath: null
  queryParameters: {}
  headers:
    Content-Type: "application/json"
  cookies: null
  body:
    name: "Kotlin"
    price: "120"
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    url: null
    body: []
    headers: []
    queryParameters: []
    cookies: []
    multipart: null
  multipart: null
response:
  status: 200
  headers:
    Content-Type: "application/json"
  cookies: null
  body:
    id: "dc8493d6-e2e3-47da-a806-d1e8ff7cd4df"
    name: "Kotlin"
    price: "120"
    stock: 0
  bodyFromFile: null
  bodyFromFileAsBytes: null
  matchers:
    body: []
    headers: []
    cookies: []
  async: false
  fixedDelayMilliseconds: null
input: null
outputMessage: null
description: null
label: null
name: "shoudCreateBookIntoInventory"
priority: null
ignored: false
